- language:
    name: 'Language'
    description: "The language to be used by TinyCI."
    type: String
    default: <%= YAML.load(File.read("#{RAILS_ROOT}/config/language.yml"))['language'] rescue 'en' %>
    values:
      - en
      - de
- base_path:
    name: 'Base Path'
    description: "The default path under which builds are checked out. This can be overridden per slave."
    type: String
    default: <%= ENV['HOME'] %>/tiny_ci
- environment:
    name: 'Environment Variables'
    description: "Default Environment variables for all builds."
    type: Hash
    default:
      CI_SERVER: TinyCI
- site_root:
    name: 'Base URL'
    description: "The URL under which TinyCI runs. This is used for URLs sent in E-Mails."
    type: String
    default: localhost:7199

- email_sender_address:
    name: 'E-Mail Sender Address'
    type: String
    default: tiny_ci@example.com
- email_address:
    name: 'SMTP Server'
    type: String
    default: "example.com"
- email_port:
    name: 'SMTP Port'
    type: Integer
    default: 25
- email_domain:
    name: 'SMTP Domain'
    description: "If you need to specify a HELO domain, you can do it here."
    type: String
    default: "localhost"
- email_user_name:
    name: 'SMTP User Name'
    type: String
    default: "tiny_ci@imedo.de"
- email_password:
    name: 'SMTP Password'
    type: String
    default: "password"
- email_authentication:
    name: 'SMTP Authentication Type'
    description: "If your mail server requires authentication, you need to specify the authentication type here."
    type: String
    default: login
    values:
      - plain
      - login
      - cram_md5
