{{- if .Values.runnerNamespace.create -}}
{{- $ns := include "tiny-ci.runnerNamespace" . -}}
{{- if ne $ns .Release.Namespace -}}
apiVersion: v1
kind: Namespace
metadata:
  name: {{ $ns }}
  labels:
    {{- include "tiny-ci.labels" . | nindent 4 }}
    app.kubernetes.io/component: runners
    {{- with .Values.runnerNamespace.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.runnerNamespace.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end -}}
{{- end -}}
