development:
  adapter: mysql
  username: root
  password:
  encoding: utf8
  host: localhost
  database: tiny_ci_development

test: &TEST
  adapter: mysql
  username: root
  password:
  encoding: utf8
  host: localhost
  database: tiny_ci_test

cucumber:
  <<: *TEST
