#!/usr/bin/env ruby
require 'rubygems'
require 'daemons'

app_root = File.expand_path(File.dirname(__FILE__) + '/..')
script_file = File.join(File.expand_path(app_root), 'script', 'simple_ci')
tmp_dir = File.join(File.expand_path(app_root), 'tmp', 'pids')

options = {
  :app_name   => "simple_ci",
  :dir_mode   => :normal,
  :dir        => tmp_dir,
  :multiple   => false,
  :ontop      => false,
  :mode       => :load,
  :backtrace  => true,
  :monitor    => false,
  :log_output => true
}

Daemons.run(script_file, options)
