#!/usr/bin/env ruby
require File.dirname(__FILE__) + '/../config/environment'
require 'drb'

DRb.start_service "druby://localhost:2250", SimpleCI::Scheduler::Server.instance

SimpleCI::Scheduler::Server.run
