#!/usr/bin/env ruby
require 'shell/system-command'
require 'shell'

app_root = File.expand_path(File.dirname(__FILE__) + '/..')
Dir.chdir(app_root)

commands = [
  "script/server",
  "script/queue",
  "juggernaut -c config/juggernaut.yml"
]

pids = commands.map do |command|
  fork { exec *command.split(' ') }
end

at_exit do
  pids.each do |pid|
    Process.kill("TERM", pid)
  end
end

sleep
