#!/usr/bin/env ruby
app_root = File.expand_path(File.dirname(__FILE__) + '/..')
Dir.chdir(app_root)

# setup if database file does not exist
unless File.exist?('config/database.yml')
  ENV['SETUP'] = 'true'
  system "script/server -p 7199"
  ENV['SETUP'] = 'false'
end

commands = [
  "script/server -p 7199",
  "script/scheduler",
  "juggernaut -c config/juggernaut.yml"
]

pids = commands.map do |command|
  fork { exec *command.split(' ') }
end

at_exit do
  pids.each do |pid|
    Process.kill("TERM", pid)
  end
end

sleep
